### ISSUE TITLE
Remove all unnecessary comments

### ISSUE THREAD

**Issue by whitehatdevv** [iBigBitDev97/traffic-light-react#1]
https://github.com/iBigBitDev97/traffic-light-react/blob/be558b0b989295a9f2c604601e29ee6617403b07/src/js/index.js#L1

Please keep in mind that have tons of unnecessary comments is a petty big mistake when you are learning, it obvious that the following example import a component. I don't want you to comment a lot, I only want that you comment code which can cause some misunderstands. 

```js
import Home from '../home.jsx'
```

PD: Please remove all the comments from all the files of the project, close the issue and please resend the assignment via BreathCode.

**Comment by iBigBitDev97** [comment]
Ready!

**Comment by whitehatdevv** [comment]
Please read carefully the instructions which say: "Please close the issue". Don't forget to follow the instructions you want to go really fast :)
