### ISSUE TITLE
What is the function of Home Component?

### ISSUE THREAD

**Issue by whitehatdevv** [iBigBitDev97/traffic-light-react#2]
https://github.com/iBigBitDev97/traffic-light-react/blob/be558b0b989295a9f2c604601e29ee6617403b07/src/js/component/home.jsx#L1

I gave you clear instructions about how to proceed if Home component is not needed, here I see an empty home which hasn't any functionality only construct the `TrafficLight` component. Please keep in mind make your exercises as best you can, if I give you some instructions later you have sent an exercises and you know I haven't look at it, please change the code and correct the exercise. It'll allow you to grow as a professional. Don't focus on deliver all the assignments ASAP, please focus on make the assignments such a real work, if not when you have to fight with a real project you will run away 😄.

You must remove the `Home` component and remove all the unnecessary comments if there is any, when you have finished please close this issue and deliver the assignment again :)

**Comment by iBigBitDev97** [comment]
i made it !

**Comment by whitehatdevv** [comment]
The same, you have not ready the instructions I have written you
